[window]
padding.x = 8
padding.y = 4
dynamic_padding = true

decorations = "None"

opacity = 0.80
blur = true

[scrolling]
history = 5000
multiplier = 5

[font]
normal.family = "Agave Nerd Font"
# bold.family
# italic.family
# bold_italic.family

size = 12
offset.x = 1
offset.y = 2

[cursor]
style.blinking = "On"
vi_mode_style.blinking = "On"
blink_interval = 450

[mouse]
hide_when_typing = true

# [keyboard]
# bindings = [
#     { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
#     { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
# ]
